# Generated by Django 3.1.4 on 2021-02-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craftapp', '0002_admin_tb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin_tb',
            name='email',
        ),
        migrations.AddField(
            model_name='admin_tb',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
    ]
