# Generated by Django 3.1.4 on 2021-02-17 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('craftapp', '0005_product_tb_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('email', models.CharField(default='', max_length=30)),
                ('number', models.CharField(default='', max_length=100)),
                ('subject', models.CharField(default='', max_length=30)),
                ('message', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='rating_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(default='', max_length=30)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='craftapp.product_tb')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='craftapp.user_tb')),
            ],
        ),
    ]
