# Generated by Django 3.1.4 on 2021-02-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craftapp', '0007_auto_20210218_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_tb',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
