# Generated by Django 3.1.4 on 2021-02-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craftapp', '0009_auto_20210220_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_tb',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
