# Generated by Django 3.1.4 on 2021-02-22 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craftapp', '0010_auto_20210221_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_tb',
            name='date',
            field=models.CharField(default='', max_length=30),
        ),
    ]
